name: Publish Docker image
on:
  push
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish 18.x/latest
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            MAVEN_VERSION=3-eclipse-temurin-11-alpine
            NODE_VERSION=18.x
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/maven-npm:3-eclipse-temurin-11-alpine-node-18
            ghcr.io/${{ github.repository_owner }}/maven-npm:latest
      - name: Build and publish 16.x
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            MAVEN_VERSION=3-jdk-11-slim
            NODE_VERSION=16.x
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/maven-npm:3-eclipse-temurin-11-alpine-node-16
